### ISSUE TITLE
Overplapping items

### ISSUE THREAD

**Issue by kanopa** [dennisameling/muuri-angular#5]
When I use data from a parent component or a photo without a precisely set height, the items overlap. If I change the width of the window, the height will be recalculated and everything will fall into place

![image](https://user-images.githubusercontent.com/42976537/88250652-e49c9980-ccb0-11ea-9ebc-ac73b1067e64.png)

**Comment by dennisameling** [comment]
@kanopa Thanks for reporting this issue! Any chance you could provide a minimal repo so I can reproduce the issue and see what needs to be fixed specifically? Thanks in advance 😊

**Comment by kanopa** [comment]
@dennisameling thanks for answer

stackblitz - https://stackblitz.com/edit/angular-ivy-zjjy9b

Elements are overlaid if you do not set the exact height for them, in the example this is a description and a photos

**Comment by dennisameling** [comment]
@kanopa Thanks for reporting back, hope I'll have some time to check in the coming days. To be continued 😊

**Comment by ubergeoff** [comment]
Though not 100% identical to your error - but I can confirm that there - have been changes to muuri > 0.8.0. that are affecting layout.

I have notices in "some instances" that the layout does not build nicely anymore in muuri 0.9.0...

@cwqt - if you revert muuri back to 0.8.0 => does this correct your issue..?

**Comment by kanopa** [comment]
> While Muuri 0.9.2 has [some fixes](https://github.com/haltu/muuri/releases) for overlapping items, it's not perfect. I still noticed items overlapping after updating, but that fixes itself when I resize my browser window.
> 
> As a workaround for now, I added a force refresh using `this.tileGrid.refresh()` in the `MuuriGridItemDirective`. Just released a new version 0.0.6 with this fix. Could you check if that resolves your issue @kanopa?

yes refresh items fix this. thank you

**Comment by dennisameling** [comment]
Great, thanks for reporting back! I'll close this issue for now. If this issue comes up again, feel free to re-open or create a new issue 😊
