### ISSUE TITLE
npm ERR! missing: html2canvas@1.0.0-rc.5

### ISSUE THREAD

**Issue by gregdorian** [dennisameling/muuri-angular#8]
this error shows when trying to install in Angular 7; also Uninstal o corrupt the libraries jspdf and file-saver

**Comment by dennisameling** [comment]
I've only tested with Angular 9+, but let me test with Angular 7 tomorrow. Thanks for your report!

**Comment by dennisameling** [comment]
Sorry, but this library only supports Angular 9 and later, as [only those versions are supported by the Angular team](https://angular.io/guide/releases#support-policy-and-schedule). Therefore I'm closing this issue. If you want to make it compatible with 7+, please feel free to provide a PR! 😊
